
version: "3.8"
services: 
    api: 
        build: ./Backend
        container_name: bxaseball-sim-backend-api
        ports: 
            - '8000:8080'
        volumes:
            - ./api:/app
            - /app/node_modules
    frontend:
        build: ./Frontend/bxaseball-webapp-frontend
        container_name: bxaseball-webapp-frontend
        ports:
            - '3000:3000'
        stdin_open: true
        tty: true

